// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickest.Infrastructure;

#nullable disable

namespace Tickest.Infrastructure.Migrations
{
    [DbContext(typeof(TickestContext))]
    partial class TickestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tickest.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("TB_AREA", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("AtendenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("AreaId");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("TB_CHAMADO", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_MENSAGEM", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Regra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_REGRA", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("TB_SETOR", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.UsuarioRegra", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RegraId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RegraId");

                    b.HasIndex("RegraId");

                    b.ToTable("TB_USUARIO_REGRA", (string)null);
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Area", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Setor", "Setor")
                        .WithMany("Areas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Chamado", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Usuario", "Analista")
                        .WithMany("ChamadosAtendimentos")
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tickest.Domain.Entities.Area", "Area")
                        .WithMany("Chamados")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickest.Domain.Entities.Usuario", "Atendente")
                        .WithMany("ChamadosAtendentes")
                        .HasForeignKey("AtendenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tickest.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("ChamadosSolicitados")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Area");

                    b.Navigation("Atendente");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Chamado", "Chamado")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickest.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Setor", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.UsuarioRegra", b =>
                {
                    b.HasOne("Tickest.Domain.Entities.Regra", "Regra")
                        .WithMany("UsuarioRegras")
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickest.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRegras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Area", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Chamado", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Regra", b =>
                {
                    b.Navigation("UsuarioRegras");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Tickest.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ChamadosAtendentes");

                    b.Navigation("ChamadosAtendimentos");

                    b.Navigation("ChamadosSolicitados");

                    b.Navigation("Mensagens");

                    b.Navigation("UsuarioRegras");
                });
#pragma warning restore 612, 618
        }
    }
}
